# Generated by Django 3.2.7 on 2021-09-23 10:07

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='abouts',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50)),
                ('content', models.TextField(max_length=550)),
            ],
        ),
        migrations.CreateModel(
            name='Book_testdrive',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=15)),
                ('email', models.EmailField(max_length=20)),
                ('contact_no', models.IntegerField(max_length=50)),
                ('Bike_model', models.IntegerField(max_length=10)),
                ('Addres', models.TextField(max_length=50)),
                ('zipcode', models.IntegerField(max_length=10)),
                ('your_question', models.TextField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='enquiries',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
                ('email', models.EmailField(max_length=20)),
                ('contact_no', models.IntegerField()),
                ('subject', models.CharField(max_length=20)),
                ('your_ques', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='More_Products',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=10)),
                ('img', models.ImageField(upload_to='')),
                ('price', models.IntegerField()),
                ('rate', models.IntegerField()),
                ('desc', models.TextField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='mycart',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user', models.CharField(max_length=10)),
                ('product_id', models.IntegerField()),
                ('quntity', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Oders',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=10)),
                ('contact_no', models.IntegerField()),
                ('addres1', models.TextField()),
                ('addres2', models.TextField()),
                ('pincode', models.IntegerField()),
                ('product_name', models.CharField(max_length=100)),
                ('time', models.DateTimeField(auto_now=True)),
                ('total', models.IntegerField(default=0)),
                ('quntitys', models.IntegerField(default=0)),
                ('prodid', models.IntegerField(default=0)),
            ],
        ),
    ]
