# Generated by Django 3.2.7 on 2021-09-23 10:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_auto_20210923_1604'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product_info',
            name='h2',
        ),
    ]
