# Generated by Django 3.2.7 on 2021-09-23 10:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0004_remove_product_info_h2'),
    ]

    operations = [
        migrations.AddField(
            model_name='product_info',
            name='h2',
            field=models.TextField(default=0, max_length=30),
            preserve_default=False,
        ),
    ]
