# Generated by Django 3.2.7 on 2021-09-23 11:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0005_product_info_h2'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product_info',
            name='field_name',
        ),
        migrations.AddField(
            model_name='product_info',
            name='h3',
            field=models.TextField(default=0, max_length=30),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='product_info',
            name='h4',
            field=models.TextField(default=0, max_length=30),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='product_info',
            name='h5',
            field=models.TextField(default=0, max_length=30),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='product_info',
            name='h6',
            field=models.TextField(default=0, max_length=30),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='product_info',
            name='h7',
            field=models.TextField(default=0, max_length=30),
            preserve_default=False,
        ),
    ]
