# Generated by Django 3.2.7 on 2021-09-23 11:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0006_auto_20210923_1641'),
    ]

    operations = [
        migrations.AddField(
            model_name='product_info',
            name='field_name',
            field=models.CharField(default=0, max_length=15),
            preserve_default=False,
        ),
    ]
