# Generated by Django 3.2.7 on 2021-09-23 11:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0007_product_info_field_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='product_info',
            name='prod_id',
            field=models.IntegerField(default=0, max_length=5),
            preserve_default=False,
        ),
    ]
