# Generated by Django 3.2.7 on 2021-09-23 14:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0008_product_info_prod_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='product_key',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('field_name', models.CharField(max_length=15)),
                ('prod_id', models.IntegerField(max_length=5)),
                ('h1', models.TextField(max_length=30)),
                ('h2', models.TextField(max_length=30)),
                ('h3', models.TextField(max_length=30)),
                ('h4', models.TextField(max_length=30)),
                ('h5', models.TextField(max_length=30)),
                ('h6', models.TextField(max_length=30)),
                ('h7', models.TextField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='product_specif',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('field_name', models.CharField(max_length=15)),
                ('prod_id', models.IntegerField(max_length=5)),
                ('h1', models.TextField(max_length=30)),
                ('h2', models.TextField(max_length=30)),
                ('h3', models.TextField(max_length=30)),
                ('h4', models.TextField(max_length=30)),
                ('h5', models.TextField(max_length=30)),
                ('h6', models.TextField(max_length=30)),
                ('h7', models.TextField(max_length=30)),
            ],
        ),
        migrations.RenameModel(
            old_name='product_info',
            new_name='product_access',
        ),
    ]
