# Generated by Django 3.2.7 on 2021-09-23 14:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0009_auto_20210923_2002'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product_key',
            old_name='field_name',
            new_name='field_namess',
        ),
        migrations.RenameField(
            model_name='product_specif',
            old_name='field_name',
            new_name='field_names',
        ),
    ]
