# Generated by Django 3.2.7 on 2021-09-23 15:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0010_auto_20210923_2006'),
    ]

    operations = [
        migrations.AddField(
            model_name='oders',
            name='price',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
