# Generated by Django 3.2.7 on 2021-09-24 12:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0013_profile'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='user_ids',
            field=models.IntegerField(default=0, max_length=10),
            preserve_default=False,
        ),
    ]
